### ISSUE TITLE
Component breaks on Vaadin 24 - NoSuchMethodError Button.addThemeVariants

### ISSUE THREAD

**Issue by paodb** [taefi/toggle-button-group#1] opened 2023-02-24 14:53 UTC
Using `toggle-button-group` with Vaadin 24.0.0.beta3 results in `NoSuchMethodError`

> java.lang.NoSuchMethodError: 'void com.vaadin.flow.component.button.Button.addThemeVariants(com.vaadin.flow.component.button.ButtonVariant[])'
> 	at org.vaadin.addons.taefi.component.ToggleButtonGroup.lambda$updateStyles$3(ToggleButtonGroup.java:357) ~[toggle-button-group-1.0.0.jar:1.0.0]

**Comment by paodb** [comment] 2023-02-24 15:02
Vaadin 24.0.0.alpha6 removes deprecated GeneratedVaadinButton (https://github.com/vaadin/flow-components/pull/4324) which had an [override](https://github.com/vaadin/flow-components/blob/24.0.0.alpha5/vaadin-button-flow-parent/vaadin-button-flow/src/main/java/com/vaadin/flow/component/button/GeneratedVaadinButton.java#L251) "required to keep binary compatibility with other 23.x minor versions"

**Comment by alexweirig** [comment] 2023-02-27 07:21
Hi,

I noticed this problem too, but I've been able to use the add-on with version 1.0.0 and beta3.

Alex

**Comment by taefi** [comment] 2023-02-27 08:45
Thanks, @paodb for reporting this. I'll fix it as soon as possible.

**Comment by taefi** [comment] 2023-03-06 07:24
@paodb @alexweirig 
This issue must be fixed by using the `2.0.0` of the component published in the directory. Let me know if there is still a problem. 

There is a non-blocker [issue](https://github.com/vaadin/flow/issues/16109) with having css under `src/main/resources/META-INF/resources/frontend` of the add-ons with v24 that produces an exception during the startup, however the component should work after the startup is complete. The issue is being investigated right now and will be fixed soon, hopefully.

**Comment by alexweirig** [comment] 2023-03-06 07:38
@taefi thank you very much for the new release of your component.

I've been testing it with 24.0.0.rc2 and the component seems to be working fine.

**Comment by taefi** [comment] 2023-03-06 07:52
Sure, thanks for reporting it. Closing the issue as fixed.

**Closed as completed by taefi** 2023-03-06 07:52 UTC
